meta {
  name: "matrix-core-architecture"
  version: "1.0.0"
  summary: "Navigate and extend the Matrix-core codebase — subsystem map, directory structure, key interfaces, Merkle/cortex/identity architecture."
  author: "Neo"
  license: "MIT"
  platforms: "linux"
}

triggers {
  keywords: "matrix-core"
  keywords: "paxlabs"
  keywords: "cortex"
  keywords: "merkle tree"
  keywords: "neo agent"
  keywords: "codegraph"
  keywords: "kvx"
  keywords: "matrix architecture"
  intents: "navigate_matrix_core"
  intents: "extend_matrix_core"
  intents: "understand_matrix"
  patterns: "matrix.core"
  patterns: "(navigate|understand|extend) .*(matrix|cortex|merkle|codegraph)"
  patterns: "\\.kvx"
}

requires {
  tools {
    name: "terminal"
    required: true
  }
  tools {
    name: "write_file"
    required: true
  }
}

provides {
  capabilities: "matrix_core_navigation"
  capabilities: "matrix_core_extension"
  output_types: "go"
  output_types: ".kvx"
}

actions {
  id: "navigate_matrix_core"
  description: "Navigate and understand the Matrix-core codebase structure"
  trigger_phrases: "navigate matrix-core"
  trigger_phrases: "find where X lives in matrix"
  trigger_phrases: "matrix subsystem map"
    rules {
      text: ".kvx files in graph/ are generated codegraph output, NOT source code — navigate UP to find actual .go files"
      priority: CRITICAL
    }
    rules {
      text: "Never modify graph/ .kvx files — they are regenerated by the codegraph tool"
      priority: CRITICAL
    }
    rules {
      text: "Snapshot OverallRoot is deterministic — changing ComputeOverallRoot() requires SchemaVersion bump"
      priority: HIGH
    }
    rules {
      text: "Identity preamble changes require IdentityVersion bump or compile-cache entries go stale"
      priority: HIGH
    }
    rules {
      text: "Cortex keys use fixed-width big-endian encoding — don't introduce variable-width fields without namespace design"
      priority: HIGH
    }
    rules {
      text: "The merkle tree domain-separates leaf and node hashes — never mix them"
      priority: NORMAL
    }
    data {
      key: "key_subsystems"
      list_value {
        items {
          string_value: "Merkle Tree (codegraph/merkle/) — BLAKE3 content-addressed tree over repo"
        }
        items {
          string_value: "Self-Model (codegraph/selfmodel/) — Artifact with Summary, Merkle, Scope"
        }
        items {
          string_value: "Snapshot System (cortex/snapshot/) — MMR + SMT → SnapshotManifest"
        }
        items {
          string_value: "Identity System (MCL/llm/identity.go) — IdentityPreamble injected in every LLM call"
        }
        items {
          string_value: "Lifecycle Machine (executor/lifecycle/) — Drafting→Proposed→Accepted→Executing→Completed"
        }
        items {
          string_value: "Cortex Keys (cortex/keys/) — hierarchical Pebble key structure"
        }
      }
    }
    data {
      key: "directory_root"
      string_value: "/data/matrix-core/"
    }
    examples {
      label: "find the actual source code from a .kvx reference"
      language: "bash"
      code: "# .kvx at graph/matrix/codegraph/selfmodel.kvx describes the package\n# Real code is at codegraph/selfmodel/selfmodel.go\nls codegraph/selfmodel/"
    }
}
actions {
  id: "extend_matrix_core"
  description: "Add new capabilities to the Matrix-core codebase"
  trigger_phrases: "add feature to matrix-core"
  trigger_phrases: "extend matrix"
  trigger_phrases: "new matrix subsystem"
    rules {
      text: "New cortex namespace: add prefix to cortex/keys/keys.go, create store methods, anchor into snapshot via StageXUpdate()"
      priority: HIGH
    }
    rules {
      text: "New envelope kind: add to MCL/envelope/kinds.go, add transition to executor/lifecycle/machine.go"
      priority: HIGH
    }
    rules {
      text: "New tool for Neo: add to neo/internal/tools/tools.go, implement handler in executor/cmd/mcl-execute/"
      priority: HIGH
    }
    rules {
      text: "New codegraph enrichment: add to codegraph/enrich/, wire into cmd/codegraph/main.go"
      priority: NORMAL
    }
}

guardrails {
  text: ".kvx files are generated output — never treat as source code"
  scope: ALWAYS
}

guardrails {
  text: "Never modify graph/ .kvx files"
  scope: WRITE_OPS
}
